# Generated by Django 4.2.11 on 2026-03-07 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_hospital_email_hospital_password_hospital_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
