# Generated by Django 6.0 on 2026-03-09 07:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_hospital_email_hospital_password_hospital_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='address',
            field=models.TextField(default='Unknown'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='state',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hospital',
            name='email',
            field=models.EmailField(default='unknown@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hospital',
            name='password',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hospital',
            name='phone',
            field=models.CharField(default='Unknown', max_length=15),
            preserve_default=False,
        ),
    ]
