<<<<<<< HEAD
# Generated by Django 4.2.11 on 2026-03-11 10:04
=======
# Generated by Django 4.2 on 2026-03-10 11:51
>>>>>>> 652df91169b0af49a2284db9722f18fd5a54c09f

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('doctor_image', models.ImageField(blank=True, null=True, upload_to='doctor_images/')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='hospital.hospital')),
            ],
        ),
    ]
