# Generated by Django 6.0 on 2026-03-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_image',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_images/'),
        ),
    ]
