# Generated by Django 3.2 on 2026-03-12 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('patient', '0002_auto_20260312_1231'),
        ('appointment', '0002_alter_appointment_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='authentication.hospital'),
        ),
    ]
